<?php

if (isset($_POST['message'])) {
    $message = $_POST['message'];
    $response = "response generated by gpt";
    echo $response;
}

function input()
{
    echo "Type something\n";
    $handle = fopen("php://stdin", "r");
    return fgets($handle);
}

function output()
{
    $input = input();
    $response = "Your message: " . $input;
    echo $response;
}
