<?php

if (!empty($_POST['message'])) {
    $message = $_POST['message'];
    $response = "response generated by GPT";
    echo $response;
} else {
    $message = $_POST['message'];
    $response = "error: type a message";
    echo $response;
}
