<?php
//require "./message.php"; 

//header('Content-Type: application/json');

if (isset($_POST['message'])) {
    $message = $_POST['message'];
    $response = "response generated by gpt";
    echo $response;
    //createHistory(explode(',' ,$_GET['message']));
    //echo json_encode($_POST['message']);
}

function input()
{
    echo "Type something\n";
    $handle = fopen("php://stdin", "r");
    return fgets($handle);
}

function output()
{
    $input = input();
    $response = "Your message: " . $input;
    echo $response;
}

function createHistory($msgs){
    $message = array();
    for($i = 0; $i < sizeof($msgs); $i++){
        $role = null;
        if($i % 2 == 0)
            $role ='user';
        else
            $role = 'assistant';

        array_push($message,['role' => $role, 'content' => $msgs[$i]]);
    }
    echo json_encode(array('message' => $message));
}